### ISSUE TITLE
Problem with GetAttribute Method on DataObjects in PF 15.1

### ISSUE THREAD

**Issue by Phayax** [susantoj/powerfactory_python#1]
The GetAttribute Method of the DataObject class does not seem to work with PowerFactory 15.1.(as well as getatrr(x,y))
If used it returns the following Error:
AttributeError: 'DataObject' object has no attribute 'GetAttribute'

Maybe it should be noted to which PowerFactory version these readmes apply.

**Comment by susantoj** [comment]
Yes, good point - the Python interface in PowerFactory changed quite a bit between v15.1 to v15.2. These scripts were tested on v15.1.6.
